### ISSUE TITLE
Stop using SHA-1 hashing in the signing process as SHA-1 is now vulnerable to collision attacks in practice

### ISSUE THREAD

**Issue by underyx** [trustly/trustly-client-python#5]
See details at https://shattered.io/

**Comment by Pelleplutt** [comment]
I hear you and I have seen this. But this is not a bug in the python client library, but rather something to address in the entire Trustly product.

**Comment by underyx** [comment]
Yep, I've found no better channel of communication for this issue, though.

**Comment by perltrustly** [comment]
I am closing this as it is not something we can address in the python client code. There are plans to add alternative signatures to the API calls. Once this is in place we will reflect these changes.
