### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by dvarrazzo** [trustly/trustly-client-python#6]
The readme example suggests to use:

    api = trustly.api.signed.SignedAPI(merchant_privatekeyfile=...

there is no `merchant_privatekeyfile` parameter. Looking at the code it seems `merchant_privatekey` is to be used, which will tell apart a file name from a private key data looking at the number of lines in the string.

**Comment by perltrustly** [comment]
Ahh indeed. We changed this in order to cater for more flexible ways of loading the private key. Missing to update the documentation of course. Pushed this in ed2cdc1. 
Thank you.
